version: '3'
services:
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    depends_on:
      - db
  nestjs:
    container_name: pmone-blog-api
    image: pmone-blog-api:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  pgdata:
